version: "3.8"
services:
  app:
    image: fastapi_users
    hostname: app
    container_name: app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_SCHEME: postgres
      DB_SERVER: db
      DB_USER: postgres
      DB_PASSWORD: clave
      DB_NAME: fastapi_test

  db:
    image: postgres
    hostname: db
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: clave
      POSTGRES_USER: postgres
      POSTGRES_DB: fastapi_test
